name: Deploy to staging

on:
  push:
    branches:
      - production

jobs:
  redeploy_everything:
    name: Redeploy everything to staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        run: |
          echo "${{ secrets.SSH_AASHU_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no \
              -i ~/ssh_key ubuntu@54.234.226.248 << 'EOF'
            cd ~/bms
            git pull
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart ws-server
            pm2 restart fe-server
          EOF